gantt
  title Bootcamp schedule
  dateFormat d-hh-mm

  section new concept
  first pass  :   des1, 01-9-00,01-10-00
  toy example  :  des1, 01-10-00,01-11-00
  challenge :     des1, 01-11-00,01-12-30
  lunch   :       des1, 01-12-30,01-14-00
  mob programming   :       des1, 01-14-00,01-15-00


